spring:
  datasource:
    plataform: h2
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /testChapter/api

practice:
  ws:
    client-information: 'https://run.mocky.io/v3/e808fe9e-4fb4-414d-a9fb-c147c6e0b84c'